### ISSUE TITLE
add_import_path seems to be ignored

### ISSUE THREAD

**Issue by MichaelKloepzig** [scout-app/scout-app#139]
Hi,

I'm trying to add an import path outside of the project directory.
I'm running the App on Windows 7 and added a config.rb containing just:

```ruby
add_import_path = "C:\Users\micha\Documents\sass"
```
I also tried double backslashes and forward slashes.

When the app attempts to compile, i get an error for my import, then it lists the locations where it's looking for the import file. My configured location is not listed there.

When I remove the import from my .scss file, everything works just fine.

Thanks for your help!

**Comment by vidhill** [comment]
Probably very late for the original question but might help someone....

I was having a similar issue, finally I got this to work..

To get Scout to point at `C:\Work\Portal\maven-generated`
I put ` add_import_path "/Work/Portal/maven-generated" ` in my config.rb 

-so backslashes swapped out for forwardslashes
I'm running on Windows 7

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Ruby.

* [Scout-App 2](http://Scout-App.io) (2016)

**Comment by sasoriza** [comment]
Does this mean that the config.rb is ignored completely and add_import_path is not supported at all anymore?

**Comment by TheJaredWilcurt** [comment]
@sasoriza 

Scout-App 0.7.1 and below was built with Adobe Air, Java, and Ruby-Sass.

Scout-App 2.0.0 and above is built with NW.js, Node, and Node-Sass.

Since Version 2 and above no longer uses the Ruby version of Sass, there is no `config.rb` or any other Ruby specific features.

Also, Ruby-Sass is no longer officially maintained, active development has moved from Ruby-Sass to Dart-Sass. There is an official C port of Dart-Sass, called SassC. It maintains 1-to-1 parity with Dart-Sass. Other languages, like Node, use the LibSass bindings from SassC, so they are always in sync with SassC/Dart-Sass.

Scout-App 2 uses Node-Sass and the LibSass bindings as the engine to process Sass/Scss to CSS.

**Comment by sasoriza** [comment]
@TheJaredWilcurt

Thank you for the detailed explanation. It seems I am once again way behind..
