### ISSUE TITLE
Casually bugs when saving

### ISSUE THREAD

**Issue by npeixotoaltimax** [scout-app/scout-app#181]
Hi,

I've been using Scout for a little while now and I've encoutered this issue many times: the generated code isn't always the same depending on which file I modify last.

This implies some explanantions:

I've got several files imported through the @import direct in my main template file "template.scss".
Let's say I write this piece of code in one file imported in "template.scss":

.element{
  @include opacity(0.4);
}

Then I save the file.
Template.css is then overwritten corectly and my item has the opacity: 0.4 css directive.

BUT if I then modify another file imported in "template.scss", the directive doesn't appear anymore.

It happens with other properties, like rgba (the sass function), linear-gradient and so on.

I can't really tell what is going except the only solution I found to solve this problem is to save my file containing the related include last... It's a quick fix which doesn't work when using this directive in more than 1 imported file.

Would you know what would be going on?

I'm running SCOUT on Windows 8.1 64bits last update.

Thanks by advance.

**Comment by ArtbyArjan** [comment]
A collegue of mine is experiencing the same problem, where I am not.

We're using Scout on Windows 7 x64 to compile our (Foundation) SCSS from Sublime 2.
When he changes the Foundation settings files last, everything is correct, but when he saves our custom style file last, some styles are overruled (mostly the margins for H tags are set to 0).
Even though we have no style declarations for H tags in our custom style file.
However, no matter in what order I save my files, the output is always right!

At the moment I'm trying to find out if it has anything to do with the Java version, since my system has Java 7 installed, and he has Java 8 and he experienced the #3124 error.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
