### ISSUE TITLE
Feature request: notify on compile failure

### ISSUE THREAD

**Issue by onepartscissors** [scout-app/scout-app#240]
This app is awesome!

What would be a really great feature would be an option to have the scout app icon bounce, or the app could come to the foreground, or some form of visual "_hey there!_" when your sass fails to compile.

It would be really great to be alerted to the fact that your code hasn't compiled CSS.

Thanks!

**Comment by TheJaredWilcurt** [comment]
Desktop notifications and alerts are on our roadmap, but won't be introduced soon as it's part of Phase 5.

Quick breakdown:

* **Phase 1:** Get a functional app up and running. (Minimal Viable Product)
* **Phase 2:** Community input and bug fixes (that's you)
* **Phase 3:** Create an automated build process to allow for faster updates and deploys (In progress)
* **Phase 4:** Make a website for the app (in progress)
* **Phase 5:** New features for future versions. (waiting on Phases 1-4 to be completed).

Here's the list of features currently planned:

* [Scout-App 2 Project Roadmap: Phase 5](https://github.com/TheJaredWilcurt/scout-app/blob/Scout-App-2-Dev/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance)

Unless we find bugs between now and coming out of beta, the only thing left to change is replacing Compass's logo with [our new Scout The Puppy logo](https://github.com/mhs/scout-app/issues/186#issuecomment-223370291). Which we kind of need to do, since Compass is not built in to Scout-App 2 like it was in Scout-App 0.7. So we really shouldn't be using their logo anymore.

**Comment by TheJaredWilcurt** [comment]
Desktop notification settings for success and error messages have been added to the master branch. This will be in the next release of Scout-App.

**Comment by TheJaredWilcurt** [comment]
@onepartscissors 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
