### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Hamza-Rhaman** [scout-app/scout-app#243]
when i try to install it show that message

"The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author."

**Comment by TheJaredWilcurt** [comment]
There is a re-release available for Scout-App 2012 (0.7.1). Or you can try Scout-App 2016, which is in beta:

* https://github.com/TheJaredWilcurt/scout-app/releases

If that works for you, close this ticket.

**Comment by Max-Headroom** [comment]
When downloading from site: http://mhs.github.io/scout-app/

**Comment by TheJaredWilcurt** [comment]
@Hamza-Rhaman 
@Max-Headroom 

The official, non-beta, version of Scout-App 2016 will be released very soon. The website for it is nearly complete. Upon the site being finished and the app being released, we will submit a pull request against the existing mhs owned repo to have everything updated.

Since the app is still in beta and the site is not finished, we are not replacing the current MHS site.

* WIP - new site: http://TheJaredWilcurt.github.io/scout-app

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
