### ISSUE TITLE
Drag n Drop projects into App

### ISSUE THREAD

**Issue by grg28** [scout-app/scout-app#259]
Hi,
The new look has captivated me especially the .scss file processing time. However a few feature additions id like to see added:

i, instead of importing a project through file explorer, dragging and dropping projects in scout-app
ii, upon uploading processed css file, indicating .scss file name and line number while inspecting on the browser.

**Comment by TheJaredWilcurt** [comment]
The drag and drop project folders into the app is a good idea. I've added it to the **[Project Roadmap](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance)**. It will be in an upcoming version of Scout-App. I'll notify you when it is released.

* * *

If you want comments in your outputted CSS file that denote what Sass file was the source of that CSS rule, you can switch to "Development" mode instead of "Production" in your projects Environment settings. It will automatically do this for you and also produce Sass source maps that will allow you to edit your Sass directly in the browser.

* [Chrome Instructions](https://developers.google.com/web/tools/chrome-devtools/debug/readability/source-maps?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3)
* [Firefox Instructions](https://hacks.mozilla.org/2014/02/live-editing-sass-and-less-in-the-firefox-developer-tools/)

**Comment by grg28** [comment]
Wonderful, thanks.

**Comment by TheJaredWilcurt** [comment]
@grg28 

![drag-in-files](https://cloud.githubusercontent.com/assets/4629794/19744603/317e3140-9b9c-11e6-8898-7c0a5d9f3aee.png)

This feature is in the current `master` branch and will be in the next version of Scout-App. I'll notify you when it's released.

**Comment by TheJaredWilcurt** [comment]
Oh, and I forgot to mention, you can also drag folders to the `Scout-App.exe` and it will launch Scout-App and auto import the projects.

And you can pass them in from the command line like this:

```
Scout-App.exe "C:\path\to\project" "C:\path\to\different\project"
```

**Comment by TheJaredWilcurt** [comment]
@grg28 

The latest version of Scout-App has been released today, and these changes are in it. Give it a try and let me know if there's anything that can be improved in a new issue.

* https://github.com/scout-app/scout-app/releases/tag/v2.12.12
