### ISSUE TITLE
Hungarian Translation

### ISSUE THREAD

**Issue by w3suli** [scout-app/scout-app#287]
New hungarian translation can be found at
* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

Several lines are missing from the original google table.

**Full hungarian translated files:**
* https://github.com/w3suli/scout-app-hungarian-translated

**Comment by TheJaredWilcurt** [comment]
Thank you so much!

Several of the translation keys are missing because they will be deprecated in the next version of Scout-App. We are currently working on a new design for when you first open the app. This means text from the old design is going away and new text will replace it. Unfortunately, this is still being developed, so the language hasn't been finalized yet. But it will be soon. I'll keep you informed of when the new text is finalized.

I've added a note to the [v2.6.8 release](https://github.com/scout-app/scout-app/releases/tag/v2.6.8) of where people can download the translation files. I won't be re-releasing 2.6.9 to add Hungarian, but I will be putting it in the next version to be released which has many other new features (drag and drop projects, new FTUX, mulit-project import screen, etc.).

**Comment by w3suli** [comment]
Thank you!

I follow will the changes.
If necessary I change my language file and tell you.

(I created a theme file: https://github.com/w3suli/scout-app-w3suli-theme/)

**Comment by TheJaredWilcurt** [comment]
That's awesome! I will add the theme to the repo so it will ship in the next version of Scout-App.

**Comment by w3suli** [comment]
:).
