### ISSUE TITLE
Scout-App doesn't save environment compression setting

### ISSUE THREAD

**Issue by ComboPrime** [scout-app/scout-app#324]
OS: MacOS Sierra 10.12.3
Scout-App Version: 2.6.8

Every time I quit Scout-App, the Environment Output Style resets to Compressed without notifying me. (I keep setting it to "Compact") This is a huge issue, since the Compressed setting breaks the site on our production server.

Thanks—

**Comment by TheJaredWilcurt** [comment]
@ComboPrime 

This bug was fixed in version **2.12.12**. However, in the latest alpha code it has returned and will need to be resolved before the next release.

For now you can download the latest release (Scout-App v2.12.12).

I'll keep this issue open to ensure the bug is dealt with and doesn't come back in the next release.

**Comment by ComboPrime** [comment]
Just want to note that 2.12.12 does NOT fix this bug…

**Comment by madebycambiamentico** [comment]
in windows (10) there's the same bug. The version I refer to is the 2.12.12 portable.

**Comment by TheJaredWilcurt** [comment]
@ComboPrime @madebycambiamentico 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
