### ISSUE TITLE
Translated Scout-App, PT-BR

### ISSUE THREAD

**Issue by paulo-santana** [scout-app/scout-app#355]
Translated, corrected and black-fonted some of the pt-br translations.
I didn't find this Atomic Slider, and didn't understand the context yet, so I can't say for sure if we're done with the pt-br. Maybe its the version i've downloaded, so right now i'm cloning the latest project to see if I can finish it.

New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@paulo-santana 

![atomic-slider](https://user-images.githubusercontent.com/4629794/30566826-a48f7ada-9c9b-11e7-9ff0-8f6adc9ac99f.png)

An "atomic write" or "atomic save" is when a program only saves a small amount of data to a file, rather than re-writing the entire file when only some of it changed. However atomic saves can cause Scout-App to not see that a file has changed, and not run again. So we've added a slider to let the user set it from 0 to 700 ms delay. This should fix this issue for people using text-editors that make atomic writes.

Can you update the `pt-br` column to be correct for all translations, then delete the `pt-br-temp` column.

**Comment by TheJaredWilcurt** [comment]
If you wanted to add your name to the `TRANSLATOR` field and a link to the `TRANSLATOR_URL` feel free too.

**Comment by paulo-santana** [comment]
My...

I was thinking that 'saves' were something more like 'save money' or 'save time' than to 'save file'...
This is gonna cause a problem to other translations.

Thanks for explaining.
Now the Brazilian Portuguese translations are all correct. I deleted the temp column as well.

**Comment by TheJaredWilcurt** [comment]
@paulo-santana 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
