### ISSUE TITLE
Play button wont start

### ISSUE THREAD

**Issue by vladimirpmf** [scout-app/scout-app#378]
OS: Windows 10
Scout-App Version:  WIN_Scout-App_2.12.12
Information from Dev Tools:  

Hello, 

I have a problem with ScoutApp. When i click the play button it does nothing. No error message pops-up, no changes, simply it doesn't react to anything. Also when I try to remove folder (kitten picture opens) it can not remove it. Does it take to install some software before I open scout? Can you help me with my problem?

(Attach screenshot below)

![sass problem](https://user-images.githubusercontent.com/35190507/36959156-e89848e6-2040-11e8-8252-c2a8fc43f377.png)
![sass problem2](https://user-images.githubusercontent.com/35190507/36959157-e8b6c500-2040-11e8-9499-64b164aeeb39.png)

**Comment by TheJaredWilcurt** [comment]
A few things to check.

1. Is your `webdev` folder located in `C:\Users\vladi\Downloads`
2. It may be running, just not displaying any notifications. You can check your settings to make sure they display notifications:

![Notification Settings inside Scout-App 2](https://user-images.githubusercontent.com/4629794/36978063-4feae822-2051-11e8-82df-b36a293c7954.png)


You could also try wiping your local settings file. This will reset Scout-App, like brand new. You'll need to re-add your projects after doing this.

1. View > Dev Tools > Console
2. Type this into the console: `scout.helpers.deleteLocalSettingsFile(true);` and then press enter.

![Dev tools](https://user-images.githubusercontent.com/4629794/36978094-6e04a636-2051-11e8-9ea3-47cf70d5f4cf.png)

Also, any file that begins with an underscore (`_`) is called a "partial". They are files that are skipped by Sass processors (like Scout-App), because they only exist to be imported into other files, they should not produce an equivalent `.css` file in the output.

* [Sass Partials](https://sass-lang.com/guide#topic-4)

This means, in your `site.scss` file you would need to add a line like this:

```scss
@import "pages/_home.scss";
```

There's an example of this at the bottom of:

* http://GraphMyCSS.com

**Comment by vladimirpmf** [comment]
1. Yes my webdev folder is located in C:\Users\vladi\Downloads

2. I checked all the notification messages, and there is no changes in application (play button is not working). I tried to reset scout and it removed previous work, but after adding folder it still is stuck on the play button. 

When I cleared scout this is written. Does it have to do something with my problem?

![sass problem3](https://user-images.githubusercontent.com/35190507/36979324-64cd5730-2087-11e8-822c-3f5906bec8ad.png)

**Comment by TheJaredWilcurt** [comment]
There is something wrong with your copy of Scout-App. Chokidar is what monitors your files for changes, and then triggers Node-Sass to process changed files. That error means that Chokidar cannot be loaded and therefore Scout-App will not be able to run properly.

You should delete your copy of Scout-App, and redownload it.

**Comment by vladimirpmf** [comment]
I tried that several times. Also I tried previous versions of Scout, and always was the same problem.

**Comment by TheJaredWilcurt** [comment]
**Privledges**:

Try running as Scout-App as admin.

* * *

**Path length:**

Try extracting Scout-App's folder from the Zip file at the root of your drive, so that it is located at `C:\Scout-App\Scout-App.exe`.

* * *

**Over-protective Protection Software:**

It's possible for protection software to quarantine things during an unzip process, thus removing the files Scout-App needs to run. Check your protection software to see if it is doing this, and tell it to stop. [Chokidar](https://www.npmjs.com/package/chokidar) is not malware, it is used by thousands of libraries/projects.

* * *

**Workaround:**

If nothing else works, you can:

1. Download [Scout-App's source code](https://github.com/scout-app/scout-app/archive/master.zip)
2. Download and install [Node.js](http://nodejs.org)
3. Unzip the `scout-app-master` folder
4. Navigate to the `scout-app-master` folder in your Command Prompt via `cd` and `dir`
5. Run `npm install` (This will take several minutes)
6. Run `npm start`

**Comment by vladimirpmf** [comment]
The solution is here!

Extracting Scout-App folder on my root drive is the solution. You sir, are genius! Thank you for your help. 
I wish you all the best,
Vladimir
