### ISSUE TITLE
List index issue

### ISSUE THREAD

**Issue by scooterlord** [scout-app/scout-app#379]
Hello! First of all thanks for the lovely plugin!

I have an issue where scout returns null in the following function:

$list: (
  attr1:value1,
  attr2:value2,
);

$j: index($list, attr2 value2);
@error $j;  => returns null

Any idea what could be causing this? Code compiles fine in sassmeister:
https://www.sassmeister.com/gist/5d4e35ee7f376724d6131c53053b40a6

**Comment by TheJaredWilcurt** [comment]
@scooterlord 

This is related to the version of Node-Sass built in to Scout-App. In 2.12.12 it returns `null`, but in the latest master branch it returns `2`.

This will be fixed in the next release of Scout-App.

If you want to use it in advance:

1. Download [Node.js](http://nodejs.org)
2. Download the [latest code](https://github.com/scout-app/scout-app/archive/master.zip)
3. Extract the `scout-app-master` folder from the zip file
4. In your Command Prompt/Terminal `cd` into the `scout-app-master` folder
5. Run `npm install` (this will take a few minutes)
6. Run `npm start`

**Comment by scooterlord** [comment]
Thanks for the info! Is the release date defined for the next version?

**Comment by TheJaredWilcurt** [comment]
I have one last bug I am working on, release will occur after that. No dates set.

* * * 

I'm not sure what you mean.

You can click on the address bar in Explorer and put `cmd` then a space at the start of the `C:\whatev` address. So it looks like `cmd C:\whatever\scout-app-master`, then press enter and it will open the Command Prompt to that folder. then run `npm install` and `npm start`.

* * * 

You can also create a `Scout-App.bat` file on your desktop. Edit it in Notepad and paste this in:

```bat
cd "C:\Portable Apps\scout-app" && cls && npm start
```
Obviously, change the file path to wherever you have the folder

**Comment by scooterlord** [comment]
Thanks for getting back to me. However what I meant is that scout works with an executable, so even if I run npm install and the node modules are installed how would I use it?

**Comment by TheJaredWilcurt** [comment]
`npm start` will run it, or you can make that `scout-app.bat` file as a shortcut, or if you really want to, you can download [NW.js v0.12.3](https://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-ia32.zip) and dump it's files into the Scout-App folder. So that `nw.exe` is next to `package.json`. Then rename `nw.exe` to `Scout-App.exe`. Then you can create a shortcut for `Scout-App.exe` and customize the shortcut's icon.

**Comment by scooterlord** [comment]
Thanks for your patience and explanation! :) Have a nice weekend!

**Comment by TheJaredWilcurt** [comment]
@scooterlord 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
