### ISSUE TITLE
File to import not found or unreadable: 

### ISSUE THREAD

**Issue by WaqasBukhary** [scout-app/scout-app#409]
I have Scout-App version 2.18.16

I am working on a scss project on Visual Studio Code (Windows 10). If the project is in play mode and I save the file in visual studio code I get this error while the file is getting saved. This is happening with all files. This is not happening if the file is already saved and I click play button. Happening only while saving on play mode.

Error (0x01) File to import not found or unreadable: foldername/fileJustSaved.

**Comment by TheJaredWilcurt** [comment]
@WaqasBukhary 

This is likely related to "atomic saves". Scout-App uses `chokidar` to monitor files for changes, then runs `node-sass` on your project. We pass in an atomic save delay into chokidar based on your preferences.

Things you can try:

1. Stop all running Scout-App projects.
1. Adjust the slider in the Scout-App preferences.
1. Run the Scout-App project again and test.
1. Repeat this process with different slider settings until it works

OR

Look into enabling/disabling atomic saves in your editor.

OR

Use a different editor.

OR

Try a Sass plugin for your editor that can process your files for you instead of Scout-App.

**Comment by WaqasBukhary** [comment]
I tried all the 4 points that you suggested to fix it but with no success. I also did some google search to disable atomic saves, but seems like they don't have it for Visual Studio Code according to this [link](https://github.com/Microsoft/vscode/issues/28927).
 
You suggestion to change the editor did fix the issue, but I do not want to stop using my main editor.

I ended up using your last suggestion to install a plugin for my editor. 

'Live Sass Compiler' plugin/extension by Ritwick Dey is working... Another extension by the same author 'Live Server' made my work even more easier as it reloads the page automatically as I change the scss file, which is saving my time.

Thanks for your suggestion.
