### ISSUE TITLE
Alternative view

### ISSUE THREAD

**Issue by arieljake** [scout-app/scout-app#43]
Can I suggest an alternate mode for scout that is 100px square with a little circle that goes Green when a compile is in progress, blue when it is "cool" (no changes) and red when an error occurred (and we can click the red light/circle to expand the app).

Then we can keep it in the corner of our desktop without needed to take up space and still be able to see progress.

**Comment by TheJaredWilcurt** [comment]
Closing this issue. We started on a new version of Scout-App, and this issue was of great inspiration.

* https://github.com/scout-app/scout-app/issues/186

I actually made a video discussing these ideas and showing a wire-frame based on them.

Ultimately I found that resizing the window dynamically and smoothly was harder than I'd expected. This was very early in the experimentation phases of Scout-App 2, just seeing if the technology would even be able to do what I wanted. Eventually, for the sake of faster production speed and the desire to actually finish the project, the design was changed to look much more similar to Scout-App Classic.

There's still a possibility that these ideas could come back around in the future in the manor of a tray icon, or in a thumbnail view of all projects.
