### ISSUE TITLE
Pasting a Folder Path in "Stylesheet Directories" Prevents CSS Output

### ISSUE THREAD

**Issue by impressivewebs** [scout-app/scout-app#51]
In the "Stylesheet Directories" section of the config options for a project, if I choose the "input" folder using the "choose" button, then copy and paste the same path into the "Output folder" field, Scout doesn't seem to recognize his as a valid way to select the folder.

If I use the "choose" button for both input and output, it works fine, but if I copy and paste either of the folder paths, it won't properly overwrite the output file, even though the log seems to indicate that it's working.

Since the path is editable without the "choose" button, then it should still work this way. Otherwise, I suppose you could make the fields readonly and allow on the "choose" method for selecting folders...? I'm using version 0.6.2.

**Comment by TheJaredWilcurt** [comment]
In [Scout-App 2](http://scout-app.io) this is resolved. Typing directly into the path fields is allowed. We also have a warning message displayed to inform you that you cannot have your output match or a be a subfolder of the input.

Since Scout-App 2 uses Chokidar to monitor file changes in the input folder, then alerts Node-Sass to process the contents of the input folder recursively, that means that if you have your output file in the same folder, then it would trigger a change in Chokidar, which in turn would kick off Node-Sass again, which would trigger Chokidar to run Node-Sass which causes Chokidar to run Node-Sass which triggers Chokidar to run Node-Sass which...

And pretty soon you're in an infinite loop, your computer catches on fire and burns your mom's house down. Now I live in an apartment.

Closing this issue.
